/* eslint-disable react/prop-types */
/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useRef } from "react";
import { useGLTF } from "@react-three/drei";

import stationScene from "../../assets/3d/Station.glb";

const Station = ({props, colour}) => {

    const ref = useRef();
    const { nodes, materials } = useGLTF(stationScene);

    return (
        <group ref={ref} {...props} dispose={null}>
            <group scale={[0.5, 0.8, 0.5]}>
                <mesh
                    geometry={nodes.Cube009.geometry}
                    // material={materials.chargingStation}
                > 
                    <meshStandardMaterial color={colour}/>
                </mesh>

                <mesh
                    geometry={nodes.Cube009_1.geometry}
                    material={materials.chargingStationLight}
                />
            </group>
        </group>
    );
}

export default Station;
