/* eslint-disable react/prop-types */
/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useRef } from "react";
import { useGLTF } from "@react-three/drei";

import streetLightScene from "../../assets/3d/StreetLight.glb";

const StreetLight = (props) => {

    const ref = useRef();
    const { nodes, materials } = useGLTF(streetLightScene);

    return (
        <group ref={ref} {...props} dispose={null}>

            <group scale={[0.18, 0.28, 0.18]}>
                <mesh
                    geometry={nodes.Cylinder001.geometry}
                    material={materials["frameLight.094"]}
                />
                <mesh
                    geometry={nodes.Cylinder001_1.geometry}
                    material={materials["cement.001"]}
                />
                <mesh
                    geometry={nodes.Cylinder001_2.geometry}
                    material={materials["frame.7449"]}
                />
                <mesh
                    geometry={nodes.Cylinder001_3.geometry}
                    material={materials["frameLight.095"]}
                />
            </group>
        </group>
    );
}

export default StreetLight;
