/* eslint-disable react/prop-types */
/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useRef } from "react";
import { useGLTF } from "@react-three/drei";

import trafficR from "../../assets/3d/TrafficLightR.glb";

const TrafficLightR = (props) => {

    const ref = useRef();
    const { nodes, materials } = useGLTF(trafficR);

    return (
        <group ref={ref} {...props} dispose={null}>
            <group scale={[0.15, 3, 0.15]}>
                <mesh
                    geometry={nodes.Cylinder012.geometry}
                    material={materials["frame.7454"]}
                />
                <mesh
                    geometry={nodes.Cylinder012_1.geometry}
                    material={materials["frameLight.105"]}
                />
                <mesh
                    geometry={nodes.Cylinder012_2.geometry}
                    material={materials["trafficBox.005"]}
                />
                <mesh
                    geometry={nodes.Cylinder012_3.geometry}
                    material={materials["yellowLight.005"]}
                />
                <mesh
                    geometry={nodes.Cylinder012_4.geometry}
                    material={materials["greenLight.005"]}
                />
                <mesh
                    geometry={nodes.Cylinder012_5.geometry}
                    material={materials["frameLight.104"]}
                />
                <mesh
                    geometry={nodes.Cylinder012_6.geometry}
                    material={materials["redLight.005"]}
                />
            </group>
        </group>
    );
}

export default TrafficLightR;
