/* eslint-disable react/prop-types */
/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useRef } from "react";
import { useGLTF } from "@react-three/drei";

import trafficL from "../../assets/3d/TrafficLightL.glb";

const TrafficLightL = (props) => {

    const ref = useRef();
    const { nodes, materials } = useGLTF(trafficL);

    return (
        <group ref={ref} {...props} dispose={null}>
            <group scale={[0.15, 3, 0.15]}>
                <mesh
                    geometry={nodes.Cylinder008.geometry}
                    material={materials["frame.7450"]}
                />
                <mesh
                    geometry={nodes.Cylinder008_1.geometry}
                    material={materials["frameLight.097"]}
                />
                <mesh
                    geometry={nodes.Cylinder008_2.geometry}
                    material={materials["greenLight.002"]}
                />
                <mesh
                    geometry={nodes.Cylinder008_3.geometry}
                    material={materials["frameLight.096"]}
                />
                <mesh
                    geometry={nodes.Cylinder008_4.geometry}
                    material={materials["trafficBox.002"]}
                />
                <mesh
                    geometry={nodes.Cylinder008_5.geometry}
                    material={materials["redLight.002"]}
                />
                <mesh
                    geometry={nodes.Cylinder008_6.geometry}
                    material={materials["yellowLight.002"]}
                />
            </group>
        </group>
    );
}

export default TrafficLightL;
