/* eslint-disable react/prop-types */
/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useRef } from "react";
import { useGLTF } from "@react-three/drei";

import treeScene from "../../assets/3d/Tree.glb";

const Tree = (props) => {

    const treeRef = useRef();
    const { nodes, materials } = useGLTF(treeScene);

    return (
        <group ref={treeRef} {...props} dispose={null}>
            <group scale={[0.8, 1.2, 0.8]}>
                <mesh
                    geometry={nodes.Icosphere001.geometry}
                    material={materials.treeBush}
                >
                    <meshStandardMaterial color={'#9CDC8C'}/>
                </mesh>
                <mesh
                    geometry={nodes.Icosphere001_1.geometry}
                    material={materials.treeTrunk}
                >
                    <meshStandardMaterial color={'#D17E3F'}/>    
                </mesh>
                <mesh
                    geometry={nodes.Icosphere001_2.geometry}
                    material={materials.cement}
                />
                <mesh
                    geometry={nodes.Icosphere001_3.geometry}
                    material={materials.cement}
                />
            </group>
        </group>
    );
}

export default Tree;
