/* eslint-disable react/prop-types */
/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useRef } from "react";
import { useGLTF } from "@react-three/drei";

import LBuildingScene2 from '../../assets/3d/BuildingL2.glb'

const LBuilding2 = ({props, glassColour, frameColour, wallColour}) => {

    const buildingRef = useRef()
    const {nodes, materials} = useGLTF(LBuildingScene2)

    return (
        <group ref={buildingRef} {...props} dispose={null}>

            <mesh
                geometry={nodes.Plane7565.geometry}
                // material={materials["roof_L.006"]}
            >
                <meshStandardMaterial color={wallColour}/>
            </mesh>
            <mesh
                geometry={nodes.Plane7565_1.geometry}
                // material={materials["glass_L.005"]}
            >
                <meshStandardMaterial color={glassColour}/>
            </mesh>
            <mesh
                geometry={nodes.Plane7565_2.geometry}
                // material={materials["frame_L.068"]}
            >
                <meshStandardMaterial color={frameColour}/>
            </mesh>
            <mesh
                geometry={nodes.Plane7565_3.geometry}
                // material={materials["wall_L.007"]}
            >
                <meshStandardMaterial color={wallColour}/>
            </mesh>

        </group>
    )
}

export default LBuilding2