/* eslint-disable react/prop-types */
/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useRef } from "react";
import { useGLTF } from "@react-three/drei";

import LBuildingScene from '../../assets/3d/BuildingL.glb'

const LBuilding = ({props, colour}) => {

    const buildingRef = useRef()
    const {nodes, materials} = useGLTF(LBuildingScene)

    return (
        <group ref={buildingRef} {...props} dispose={null}>

            <group rotation={[-Math.PI / 2, Math.PI / 2, 0]} scale={[1, 1, 0.5]}>
                <mesh
                    geometry={nodes.Building_L_1.geometry}
                    // material={materials.wall_L}
                >
                    <meshStandardMaterial color={colour}/>
                </mesh>

                <mesh
                    geometry={nodes.Building_L_2.geometry}
                    material={materials.glass_L}
                />
                <mesh
                    geometry={nodes.Building_L_3.geometry}
                    material={materials.frame_L}
                />
                <mesh
                    geometry={nodes.Building_L_4.geometry}
                    // material={materials.roof_L}
                >
                    <meshStandardMaterial color={colour}/>
                </mesh>
            </group>

        </group>
    )
}

export default LBuilding