/* eslint-disable react/prop-types */
/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useRef } from "react";
import { useGLTF } from "@react-three/drei";

import rectBuildingScene2 from '../../assets/3d/BuildingI2.glb'

const RectBuilding2 = ({props, glassColour, frameColour, wallColour}) => {

    const buildingRef = useRef()
    const {nodes, materials} = useGLTF(rectBuildingScene2)

    return (
        <group ref={buildingRef} {...props} dispose={null}>
            <group rotation={[Math.PI / 2, -Math.PI / 2, 0]}>
                <mesh
                    geometry={nodes.Building_I_b_1.geometry}
                    // material={materials["wall_I.093"]}
                >
                    <meshStandardMaterial color={wallColour}/>
                </mesh>
                <mesh
                    geometry={nodes.Building_I_b_2.geometry}
                    // material={materials["glass_I.067"]}
                >
                    <meshStandardMaterial color={glassColour}/>
                </mesh>
                <mesh
                    geometry={nodes.Building_I_b_3.geometry}
                    // material={materials["frame_I.067"]}
                >
                    <meshStandardMaterial color={frameColour}/>
                </mesh>
                <mesh
                    geometry={nodes.Building_I_b_4.geometry}
                    // material={materials["roof_I.018"]}
                >
                    <meshStandardMaterial color={wallColour}/>
                </mesh>
            </group>
    </group>
    )
}

export default RectBuilding2