/* eslint-disable react/prop-types */
/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useRef } from "react";
import { useGLTF } from "@react-three/drei";

import squareBuildingScene from '../../assets/3d/BuildingA.glb'

const SquareBuilding = ({props, glassColour, frameColour, wallColour}) => {
    
    const buildingRef = useRef()
    const {nodes, materials} = useGLTF(squareBuildingScene)
    
    return (
        <group ref={buildingRef} {...props} dispose={null}>

            <group rotation={[Math.PI / 2, -Math.PI / 2, 0]}>
                <mesh
                    geometry={nodes.Building_1001.geometry}
                    material={materials["awning1.005"]}
                />
                <mesh
                    geometry={nodes.Building_1001_1.geometry}
                    // material={materials["glass1.004"]}
                >
                    <meshStandardMaterial color={glassColour}/>
                </mesh>
                <mesh
                    geometry={nodes.Building_1001_2.geometry}
                    material={materials["frame1.005"]}
                >
                    <meshStandardMaterial color={frameColour}/>    
                </mesh>
                <mesh
                    geometry={nodes.Building_1001_3.geometry}
                    // material={materials["Roof.003"]}
                >
                    <meshStandardMaterial color={wallColour}/>
                </mesh>
                
                <mesh
                    geometry={nodes.Building_1001_4.geometry}
                    // material={materials["Wall1.006"]}
                >
                    <meshStandardMaterial color={wallColour}/>
                </mesh>
            </group>
        </group>
    )
}

export default SquareBuilding
