/* eslint-disable react/prop-types */
/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useRef } from "react";
import { useGLTF } from "@react-three/drei";

import UBuildingScene from '../../assets/3d/BuildingU.glb'

const UBuilding = ({props, colour}) => {
    const buildingRef = useRef()
    const {nodes, materials} = useGLTF(UBuildingScene)

    return (
        <group ref={buildingRef} {...props} dispose={null}>

            <group rotation={[-Math.PI / 2, 0, Math.PI]}>
                <mesh
                    geometry={nodes.Building_U_1.geometry}
                    // material={materials["wall_U.108"]}
                >
                    <meshStandardMaterial color={colour}/>
                </mesh>

                <mesh
                    geometry={nodes.Building_U_2.geometry}
                    material={materials["glass_U.097"]}
                />
                <mesh
                    geometry={nodes.Building_U_3.geometry}
                    material={materials["frame_U.097"]}
                />
                <mesh
                    geometry={nodes.Building_U_4.geometry}
                    // material={materials["roof_U.001"]}
                >
                    <meshStandardMaterial color={colour}/>
                </mesh>
            </group>
        </group>
    )
}

export default UBuilding