/* eslint-disable react/prop-types */
/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useRef } from "react";
import { useGLTF } from "@react-three/drei";

import ZBuildingScene2 from '../../assets/3d/BuildingZ2.glb'

const ZBuilding2 = ({props, glassColour, frameColour, wallColour}) => {
    const buildingRef = useRef()
    const {nodes, materials} = useGLTF(ZBuildingScene2)

    return (
        <group ref={buildingRef} {...props} dispose={null}>

        <group scale={[0.2, 0.15, 0.4]}>
            <mesh
                geometry={nodes.Building_Z_b_1.geometry}
                material={materials["awning_Z.001"]}
            />
            <mesh
                geometry={nodes.Building_Z_b_2.geometry}
                // material={materials.wall_Z}
            >
                <meshStandardMaterial color={wallColour}/>
            </mesh>
            <mesh
                geometry={nodes.Building_Z_b_3.geometry}
                // material={materials.frame_Z}
            >
                <meshStandardMaterial color={frameColour}/>
            </mesh>
            <mesh
                geometry={nodes.Building_Z_b_4.geometry}
                // material={materials.glass_Z}
            >
                <meshStandardMaterial color={glassColour}/>
            </mesh>
            <mesh
                geometry={nodes.Building_Z_b_5.geometry}
                // material={materials["roof_Z.001"]}
            >
                <meshStandardMaterial color={wallColour}/>
            </mesh>
            <mesh
                geometry={nodes.Building_Z_b_6.geometry}
                material={materials["door_handle_Z.001"]}
            />
        </group>

        </group>
    )
}

export default ZBuilding2