/* eslint-disable react/no-unknown-property */
import { useRef, useEffect, useLayoutEffect } from "react";
import { useGLTF, Text } from "@react-three/drei";
import { useFrame, useThree } from "@react-three/fiber";

import allCarsScene from "../assets/3d/ALLCARS.glb";

const AllCars = (props) => {

    const allCars = useRef();
    const { nodes, materials } = useGLTF(allCarsScene);

    return (
        <group ref={allCars} {...props} dispose={null}>

            <group position={[6.292, 0, 0]}>
                <mesh
                    castShadow
                    receiveShadow
                    material-metalness={0}
                    geometry={nodes.mesh_16.geometry}
                    material={nodes.mesh_16.material}
                />
                <mesh
                    castShadow
                    receiveShadow
                    material-metalness={0}
                    geometry={nodes.mesh_17.geometry}
                    material={nodes.mesh_17.material}
                />
                <mesh
                    castShadow
                    receiveShadow
                    material-metalness={0}
                    geometry={nodes.mesh_18.geometry}
                    material={nodes.mesh_18.material}
                />
                <mesh
                    castShadow
                    receiveShadow
                    material-metalness={0}
                    geometry={nodes.mesh_19.geometry}
                    material={nodes.mesh_19.material}
                />
                {/* <mesh
                    castShadow
                    receiveShadow
                    material-metalness={0}
                    geometry={nodes.mesh_20.geometry}
                    material={nodes.mesh_20.material}
                /> */}
                <mesh
                    castShadow
                    receiveShadow
                    material-metalness={0}
                    geometry={nodes.mesh_21.geometry}
                    material={nodes.mesh_21.material}
                />
                <mesh
                    castShadow
                    receiveShadow
                    material-metalness={0}
                    geometry={nodes.mesh_22.geometry}
                    material={nodes.mesh_22.material}
                />
                <mesh
                    castShadow
                    receiveShadow
                    material-metalness={0}
                    geometry={nodes.mesh_12.geometry}
                    material={nodes.mesh_12.material}
                />
                <mesh
                    castShadow
                    receiveShadow
                    material-metalness={0}
                    geometry={nodes.mesh_13.geometry}
                    material={nodes.mesh_13.material}
                />
                <mesh
                    castShadow
                    receiveShadow
                    material-metalness={0}
                    geometry={nodes.mesh_14.geometry}
                    material={nodes.mesh_14.material}
                />
                <mesh
                    castShadow
                    receiveShadow
                    material-metalness={0}
                    geometry={nodes.mesh_15.geometry}
                    material={nodes.mesh_15.material}
                />
            </group>
            <group position={[4.198, 0, 0]}>
                {/* <mesh
                    castShadow
                    receiveShadow
                    material-metalness={0}
                    geometry={nodes.mesh_23.geometry}
                    material={nodes.mesh_23.material}
                /> */}
                <mesh
                    castShadow
                    receiveShadow
                    material-metalness={0}
                    geometry={nodes.mesh_24.geometry}
                    material={nodes.mesh_24.material}
                />
                <mesh
                    castShadow
                    receiveShadow
                    material-metalness={0}
                    geometry={nodes.mesh_25.geometry}
                    material={nodes.mesh_25.material}
                />
                <mesh
                    castShadow
                    receiveShadow
                    material-metalness={0}
                    geometry={nodes.mesh_26.geometry}
                    material={nodes.mesh_26.material}
                />
                <mesh
                    castShadow
                    receiveShadow
                    material-metalness={0}
                    geometry={nodes.mesh_27.geometry}
                    material={nodes.mesh_27.material}
                />
                <mesh
                    castShadow
                    receiveShadow
                    material-metalness={0}
                    geometry={nodes.mesh_28.geometry}
                    material={nodes.mesh_28.material}
                />
                <mesh
                    castShadow
                    receiveShadow
                    material-metalness={0}
                    geometry={nodes.mesh_29.geometry}
                    material={nodes.mesh_29.material}
                />
            </group>
            <group position={[2.093, 0, 0]}>
                <mesh
                    castShadow
                    receiveShadow
                    material-metalness={0}
                    geometry={nodes.mesh_30.geometry}
                    material={nodes.mesh_30.material}
                />
                <mesh
                    castShadow
                    receiveShadow
                    material-metalness={0}
                    geometry={nodes.mesh_31.geometry}
                    material={nodes.mesh_31.material}
                />
                {/* <mesh
                    castShadow
                    receiveShadow
                    material-metalness={0}
                    geometry={nodes.mesh_32.geometry}
                    material={nodes.mesh_32.material}
                /> */}
                <mesh
                    castShadow
                    receiveShadow
                    material-metalness={0}
                    geometry={nodes.mesh_33.geometry}
                    material={nodes.mesh_33.material}
                />
                <mesh
                    castShadow
                    receiveShadow
                    material-metalness={0}
                    geometry={nodes.mesh_34.geometry}
                    material={nodes.mesh_34.material}
                />
                <mesh
                    castShadow
                    receiveShadow
                    material-metalness={0}
                    geometry={nodes.mesh_35.geometry}
                    material={nodes.mesh_35.material}
                />
                <mesh
                    castShadow
                    receiveShadow
                    material-metalness={0}
                    geometry={nodes.mesh_36.geometry}
                    material={nodes.mesh_36.material}
                />
            </group>
            <group position={[-4.193, -0.004, 0.004]}>
                {/* <mesh
                    castShadow
                    receiveShadow
                    material-metalness={0}
                    geometry={nodes.mesh_37.geometry}
                    material={nodes.mesh_37.material}
                /> */}
                <mesh
                    castShadow
                    receiveShadow
                    material-metalness={0}
                    geometry={nodes.mesh_38.geometry}
                    material={nodes.mesh_38.material}
                />
                <mesh
                    castShadow
                    receiveShadow
                    material-metalness={0}
                    geometry={nodes.mesh_39.geometry}
                    material={nodes.mesh_39.material}
                />
                <mesh
                    castShadow
                    receiveShadow
                    material-metalness={0}
                    geometry={nodes.mesh_40.geometry}
                    material={nodes.mesh_40.material}
                />
                <mesh
                    castShadow
                    receiveShadow
                    material-metalness={0}
                    geometry={nodes.mesh_41.geometry}
                    material={nodes.mesh_41.material}
                />
                <mesh
                    castShadow
                    receiveShadow
                    material-metalness={0}
                    geometry={nodes.mesh_42.geometry}
                    material={nodes.mesh_42.material}
                />
                <mesh
                    castShadow
                    receiveShadow
                    material-metalness={0}
                    geometry={nodes.mesh_43.geometry}
                    material={nodes.mesh_43.material}
                />
            </group>
            <group position={[-2.079, 0, 0]}>
                {/* <mesh
                    castShadow
                    receiveShadow
                    material-metalness={0}
                    geometry={nodes.mesh_44.geometry}
                    material={nodes.mesh_44.material}
                /> */}
                <mesh
                    castShadow
                    receiveShadow
                    material-metalness={0}
                    geometry={nodes.mesh_45.geometry}
                    material={nodes.mesh_45.material}
                />
                <mesh
                    castShadow
                    receiveShadow
                    material-metalness={0}
                    geometry={nodes.mesh_46.geometry}
                    material={nodes.mesh_46.material}
                />
                <mesh
                    castShadow
                    receiveShadow
                    material-metalness={0}
                    geometry={nodes.mesh_47.geometry}
                    material={nodes.mesh_47.material}
                />
                <mesh
                    castShadow
                    receiveShadow
                    material-metalness={0}
                    geometry={nodes.mesh_48.geometry}
                    material={nodes.mesh_48.material}
                />
                <mesh
                    castShadow
                    receiveShadow
                    material-metalness={0}
                    geometry={nodes.mesh_53.geometry}
                    material={nodes.mesh_53.material}
                />
                <mesh
                    castShadow
                    receiveShadow
                    material-metalness={0}
                    geometry={nodes.mesh_49.geometry}
                    material={nodes.mesh_49.material}
                />
                <mesh
                    castShadow
                    receiveShadow
                    material-metalness={0}
                    geometry={nodes.mesh_50.geometry}
                    material={nodes.mesh_50.material}
                />
                <mesh
                    castShadow
                    receiveShadow
                    material-metalness={0}
                    geometry={nodes.mesh_51.geometry}
                    material={nodes.mesh_51.material}
                />
                <mesh
                    castShadow
                    receiveShadow
                    material-metalness={0}
                    geometry={nodes.mesh_52.geometry}
                    material={nodes.mesh_52.material}
                />
            </group>
            {/* <mesh
                castShadow
                receiveShadow
                material-metalness={0}
                geometry={nodes.mesh_0.geometry}
                material={nodes.mesh_0.material}
            /> */}
            <mesh
                castShadow
                receiveShadow
                material-metalness={0}
                geometry={nodes.mesh_1.geometry}
                material={nodes.mesh_1.material}
            />
            <mesh
                castShadow
                receiveShadow
                material-metalness={0}
                geometry={nodes.mesh_2.geometry}
                material={nodes.mesh_2.material}
            />
            <mesh
                castShadow
                receiveShadow
                material-metalness={0}
                geometry={nodes.mesh_3.geometry}
                material={nodes.mesh_3.material}
            />
            <mesh
                castShadow
                receiveShadow
                material-metalness={0}
                geometry={nodes.mesh_4.geometry}
                material={nodes.mesh_4.material}
                rotation={[0, Math.PI / 2, 0]}
            />
            <mesh
                castShadow
                receiveShadow
                material-metalness={0}
                geometry={nodes.mesh_5.geometry}
                material={nodes.mesh_5.material}
            />
            <mesh
                castShadow
                receiveShadow
                material-metalness={0}
                geometry={nodes.mesh_6.geometry}
                material={nodes.mesh_6.material}
            />
            <mesh
                castShadow
                receiveShadow
                material-metalness={0}
                geometry={nodes.mesh_7.geometry}
                material={nodes.mesh_7.material}
            />
            <mesh
                castShadow
                receiveShadow
                material-metalness={0}
                geometry={nodes.mesh_8.geometry}
                material={nodes.mesh_8.material}
            />
            <mesh
                castShadow
                receiveShadow
                material-metalness={0}
                geometry={nodes.mesh_9.geometry}
                material={nodes.mesh_9.material}
            />
            <mesh
                castShadow
                receiveShadow
                material-metalness={0}
                geometry={nodes.mesh_10.geometry}
                material={nodes.mesh_10.material}
            />
            <mesh
                castShadow
                receiveShadow
                material-metalness={0}
                geometry={nodes.mesh_11.geometry}
                material={nodes.mesh_11.material}
            />


        </group>
    );
}

export default AllCars;