/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useRef, useEffect, useLayoutEffect } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame, useThree } from "@react-three/fiber";

import chargerScene from "../assets/3d/CHARGER.glb";

const Charger = (props) => {

    const charger = useRef();
    const { nodes, materials } = useGLTF(chargerScene);

    return (
        <group ref={charger} {...props} dispose={null}>

            <mesh
                material-metalness={0}
                geometry={nodes.mesh_0.geometry}
                material={nodes.mesh_0.material}
                >
                <meshStandardMaterial color="#C8F165" />
            </mesh>
            <mesh
                material-metalness={0}
                geometry={nodes.mesh_1.geometry}
                material={nodes.mesh_1.material}
                >
                <meshStandardMaterial color="#D3D3D3" />
            </mesh>
            <mesh
                material-metalness={0}
                geometry={nodes.mesh_2.geometry}
                material={nodes.mesh_2.material}
            />
            <mesh
                material-metalness={0}
                geometry={nodes.mesh_3.geometry}
                material={nodes.mesh_3.material}
                >
                <meshStandardMaterial color="#C8F165" />
            </mesh>
            <mesh
                material-metalness={0}
                geometry={nodes.mesh_4.geometry}
                material={nodes.mesh_4.material}
                >
                <meshStandardMaterial color="#C8F165" />
            </mesh>
            <mesh
                material-metalness={0}
                geometry={nodes.mesh_5.geometry}
                material={nodes.mesh_5.material}
                >
                <meshStandardMaterial color="#D3D3D3" />
            </mesh>
        </group>
    );
}

export default Charger;

