/* eslint-disable react/prop-types */
/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useRef, useEffect, useLayoutEffect } from "react";
import { useGLTF, Text } from "@react-three/drei";
import { useFrame, useThree } from "@react-three/fiber";

import classicBottomScene from "../assets/3d/CLASSIC-BOTTOM.glb";
import interFont from '../assets/fonts/Inter.ttf';

const ClassicBottom = ({ showLicense, license, ...props }) => {

    const classicBottom = useRef();
    const { nodes, materials } = useGLTF(classicBottomScene);

    return (
        <group ref={classicBottom} {...props} dispose={null}>
            <mesh
                material-metalness={0}
                geometry={nodes.mesh_0.geometry}
                material={nodes.mesh_0.material}
            >
                <meshStandardMaterial color={props.colour} />
            </mesh>
            <mesh
                material-metalness={0}
                geometry={nodes.mesh_1.geometry}
                material={nodes.mesh_1.material}
            />
            {/*front license*/}
            <mesh
                material-metalness={0}
                geometry={nodes.mesh_2.geometry}
                material={nodes.mesh_2.material}
            >
                {showLicense && (
                <>
                <Text
                    position={[0,0.396,2.012]}
                    color="#000000"
                    fontSize={0.08}
                    font={interFont}
                >
                    {license}
                </Text>
                </>
                )}
            </mesh>
            {/*back license*/}
            <mesh
                material-metalness={0}
                geometry={nodes.mesh_3.geometry}
                material={nodes.mesh_3.material}
                >
                {showLicense && (
                <>
                <Text
                    position={[0,0.45,-1.274]}
                    color="#000000"
                    fontSize={0.08}
                    rotation={[0, Math.PI,0]}
                    font={interFont}
                >
                  {license}
                </Text>
                </>
                )}
            </mesh>
            <mesh
                material-metalness={0}
                geometry={nodes.mesh_4.geometry}
                material={nodes.mesh_4.material}
            />


        </group>
    );
}

export default ClassicBottom;
