/* eslint-disable react/prop-types */
/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useRef, useEffect, useLayoutEffect } from "react";
import { useGLTF, Text } from "@react-three/drei";
import { useFrame, useThree } from "@react-three/fiber";

import evBottomScene from "../assets/3d/EV-BOTTOM.glb";
import interFont from '../assets/fonts/Inter.ttf';


const EVBottom = ({ showLicense, license, ...props }) => {

    const evBottom = useRef();
    const { nodes, materials } = useGLTF(evBottomScene);

    return (
        <group ref={evBottom} {...props} dispose={null}>

            {/*front license*/}
            <mesh
                material-metalness={0}
                geometry={nodes.mesh_0.geometry}
                material={nodes.mesh_0.material}
            >
           {showLicense && (
                <>
                <Text
                    position={[0,0.34,2.055]}
                    color="#000000"
                    fontSize={0.08}
                    font={interFont}
                >
                    {license}
                </Text>
                </>
                )}
                </mesh>
            {/*back license*/}
            <mesh
                material-metalness={0}
                geometry={nodes.mesh_1.geometry}
                material={nodes.mesh_1.material}
                >
                {showLicense && (
                <>
                <Text
                    position={[0,0.34,-1.225]}
                    color="#000000"
                    fontSize={0.08}
                    rotation={[0, Math.PI,0]}
                    font={interFont}
                >
                  {license}
                </Text>
                </>
                )}
                </mesh>
            <mesh
                material-metalness={0}
                geometry={nodes.mesh_2.geometry}
                material={nodes.mesh_2.material}
            />
            <mesh
                material-metalness={0}
                geometry={nodes.mesh_3.geometry}
                material={nodes.mesh_3.material}
                rotation={[0, Math.PI / 2, 0]}
            />
            <mesh
                material-metalness={0}
                geometry={nodes.mesh_4.geometry}
                material={nodes.mesh_4.material}
            >
                <meshStandardMaterial color={props.colour} />
            </mesh>

        </group>
    );
}

export default EVBottom;
