/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useRef, useEffect, useLayoutEffect } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame, useThree } from "@react-three/fiber";

import evBottomScene from "../assets/3d/EV_BOTTOM.glb";

const EVBottom = (props) => {

    const evBottom = useRef();
    const { nodes, materials } = useGLTF(evBottomScene);

    return (
        <group ref={evBottom} {...props} dispose={null}>
            <mesh
                geometry={nodes.mesh_0.geometry}
                material={nodes.mesh_0.material}
            >
            </mesh>
            <mesh
                geometry={nodes.mesh_1.geometry}
                material={nodes.mesh_1.material}
                rotation={[0, Math.PI / 2, 0]}
            >
            </mesh>
            <mesh
                geometry={nodes.mesh_2.geometry}
                material={nodes.mesh_2.material}
            >
                {/* <meshStandardMaterial color={props.colour} /> */}
            </mesh> 
            <mesh
                geometry={nodes.mesh_3.geometry}
                material={nodes.mesh_3.material}
            >
            </mesh>
        </group>
    );
}

export default EVBottom;
