/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useRef, useEffect, useLayoutEffect } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame, useThree } from "@react-three/fiber";

import evWheelsScene from "../assets/3d/EV_TIRES.glb";

const EVWheels = (props) => { 

    const evWheels = useRef();
    const { nodes, materials } = useGLTF(evWheelsScene);

  return (
    <group ref={evWheels} {...props} dispose={null}>
      <group rotation={[0, Math.PI / 2, 0]}>
        <mesh
          geometry={nodes.mesh_0.geometry}
          material={nodes.mesh_0.material}
        />
        <mesh
          geometry={nodes.mesh_1.geometry}
          material={nodes.mesh_1.material}
        />
        <mesh
          geometry={nodes.mesh_2.geometry}
          material={nodes.mesh_2.material}
        />
        <mesh
          geometry={nodes.mesh_3.geometry}
          material={nodes.mesh_3.material}
        />
      </group>
    </group>
  );
}

export default EVWheels;

