/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF, PerspectiveCamera, OrthographicCamera } from "@react-three/drei";

import evCarScene from '../assets/3d/EV.glb'

const EVCar = (props) => {
    const evCar = useRef()
    const { nodes, materials } = useGLTF(evCarScene)

    return (
        <group ref={evCar} {...props} dispose={null}>

      <group rotation={[0, Math.PI / 2, 0]}>
        <mesh
          geometry={nodes.mesh_0.geometry}
          material={nodes.mesh_0.material}
        />
        <mesh
          geometry={nodes.mesh_1.geometry}
          material={nodes.mesh_1.material}
        />
        <mesh
          geometry={nodes.mesh_2.geometry}
          material={nodes.mesh_2.material}
        />
        <mesh
          geometry={nodes.mesh_3.geometry}
          material={nodes.mesh_3.material}
        />
      </group>

      <mesh geometry={nodes.mesh_4.geometry} material={nodes.mesh_4.material} />
      <mesh geometry={nodes.mesh_5.geometry} material={nodes.mesh_5.material} />
      <mesh
        geometry={nodes.mesh_6.geometry}
        material={nodes.mesh_6.material}
        rotation={[0, Math.PI / 2, 0]}
      />
      <mesh geometry={nodes.mesh_7.geometry} material={nodes.mesh_7.material} />
      
      <mesh geometry={nodes.mesh_8.geometry} material={nodes.mesh_8.material} />
      <mesh geometry={nodes.mesh_9.geometry} material={nodes.mesh_9.material} />
      <mesh
        geometry={nodes.mesh_10.geometry}
        material={nodes.mesh_10.material}
      />
      <mesh
        geometry={nodes.mesh_11.geometry}
        material={nodes.mesh_11.material}
      />

        </group>
    )
}

export default EVCar