/* eslint-disable react/prop-types */
/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useRef, useEffect, useLayoutEffect } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame, useThree } from "@react-three/fiber";

import roundBottomScene from "../assets/3d/ROUND-BOTTOM.glb";

const RoundBottom = (props) => {

    const roundBottom = useRef();
    const { nodes, materials } = useGLTF(roundBottomScene);

    return (
        <group ref={roundBottom} {...props} dispose={null}>

            


        </group>
    );
}

export default RoundBottom;
