/* eslint-disable react/prop-types */
/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useRef, useEffect, useLayoutEffect } from "react";
import { useGLTF, Text } from "@react-three/drei";
import { useFrame, useThree } from "@react-three/fiber";

import roundBottomScene from "../assets/3d/ROUND-BOTTOM.glb";
import interFont from '../assets/fonts/Inter.ttf';

const RoundBottom = ({ showLicense, license, ...props }) => {

    const roundBottom = useRef();
    const { nodes, materials } = useGLTF(roundBottomScene);

    return (
        <group ref={roundBottom} {...props} dispose={null}>

            {/* <mesh
                geometry={nodes.mesh_0.geometry}
                material={nodes.mesh_0.material}
                material-metalness={0}
            >
                <meshStandardMaterial color={props.colour} />
            </mesh>
            <mesh
                geometry={nodes.mesh_1.geometry}
                material={nodes.mesh_1.material}
                material-metalness={0}
            >
                {showLicense && (
                <>
                <Text
                    position={[0,0.335,-1.17]}
                    color="#000000"
                    fontSize={0.08}
                    rotation={[0, Math.PI,0]}
                    font={interFont}
                >
                  {license}
                </Text>
                </>
                )}
            </mesh>
            <mesh
                geometry={nodes.mesh_2.geometry}
                material={nodes.mesh_2.material}
                material-metalness={0}
            >
                {showLicense && (
                <>
                <Text
                    position={[0,0.4,2.06]}
                    color="#000000"
                    fontSize={0.08}
                    font={interFont}
                >
                    {license}
                </Text>
                </>
                )}
            </mesh>
            <mesh
                geometry={nodes.mesh_3.geometry}
                material={nodes.mesh_3.material}
                material-metalness={0}
            /> */}

            <mesh
                material-metalness={0}
                geometry={nodes.mesh_0.geometry}
                material={nodes.mesh_0.material}
            >
                <meshStandardMaterial color={props.colour} />
            </mesh>
            <mesh
                material-metalness={0}
                geometry={nodes.mesh_1.geometry}
                material={nodes.mesh_1.material}
            />
            <mesh
                material-metalness={0}
                geometry={nodes.mesh_2.geometry}
                material={nodes.mesh_2.material}
            />
            <mesh
                material-metalness={0}
                geometry={nodes.mesh_3.geometry}
                material={nodes.mesh_3.material}
            />


        </group>
    );
}

export default RoundBottom;
