/* eslint-disable react/prop-types */
/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useRef, useEffect, useLayoutEffect } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame, useThree } from "@react-three/fiber";

import sportTopScene from "../assets/3d/SPORT-TOP.glb";

const SportTop = (props) => {

    const sportTop = useRef();
    const { nodes, materials } = useGLTF(sportTopScene);

    return (
        <group ref={sportTop} {...props} dispose={null}>

            <mesh
                geometry={nodes.mesh_0.geometry}
                material={nodes.mesh_0.material}
                position={[0.001, 0.026, 0.002]}
                material-metalness={0}
            >
                <meshStandardMaterial color={props.colour} />
            </mesh>
            <mesh
                geometry={nodes.mesh_1.geometry}
                material={nodes.mesh_1.material}
                position={[0.001, 0.026, 0.002]}
                material-metalness={0}
            />

        </group>
    );
}

export default SportTop;

