/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useRef, useEffect, useLayoutEffect } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame, useThree } from "@react-three/fiber";

import sportWheelsScene from "../assets/3d/SPORT-WHEELS.glb";

const SportWheels = (props) => {

    const sportWheels = useRef();
    const { nodes, materials } = useGLTF(sportWheelsScene);

    return (
        <group ref={sportWheels} {...props} dispose={null}>

            <mesh
                geometry={nodes.mesh_0.geometry}
                material={nodes.mesh_0.material}
                position={[0, 0, -0.213]}
                material-metalness={0}
            />
            <mesh
                geometry={nodes.mesh_1.geometry}
                material={nodes.mesh_1.material}
                material-metalness={0}
            />
            <mesh
                geometry={nodes.mesh_2.geometry}
                material={nodes.mesh_2.material}
                material-metalness={0}
            />
            <mesh
                geometry={nodes.mesh_3.geometry}
                material={nodes.mesh_3.material}
                position={[0, 0, -0.213]}
                material-metalness={0}
            />

        </group>
    );
}

export default SportWheels;

