/* eslint-disable react/prop-types */
/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useRef, useEffect, useLayoutEffect } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame, useThree } from "@react-three/fiber";

import vintageBottomScene from "../assets/3d/VINTAGE-BOTTOM.glb";

const VintageBottom = (props) => {

    const vintageBottom = useRef();
    const { nodes, materials } = useGLTF(vintageBottomScene);

    return (
        <group ref={vintageBottom} {...props} dispose={null}>

            


        </group>
    );
}

export default VintageBottom;
