/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useRef, useEffect, useLayoutEffect } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame, useThree } from "@react-three/fiber";

import vintageWheelsScene from "../assets/3d/VINTAGE-WHEELS.glb";

const VintageWheels = (props) => {

    const vintageWheels = useRef();
    const { nodes, materials } = useGLTF(vintageWheelsScene);

    return (
        <group ref={vintageWheels} {...props} dispose={null}>

            <mesh
                geometry={nodes.mesh_0.geometry}
                material={nodes.mesh_0.material}
                position={[0, 0.002, 0]}
                material-metalness={0}
            />

        </group>
    );
}

export default VintageWheels;

