/* eslint-disable react/prop-types */
/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useRef, useEffect, useLayoutEffect } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame, useThree } from "@react-three/fiber";

import vintageTopScene from "../assets/3d/VINTAGE-TOP.glb";

const VintageTop = (props) => {

    const vintageTop = useRef();
    const { nodes, materials } = useGLTF(vintageTopScene);

    return (
        <group ref={vintageTop} {...props} dispose={null}>

            <group position={[0, 0.002, 0]}>
                <mesh
                    geometry={nodes.mesh_0.geometry}
                    material={nodes.mesh_0.material}
                    material-metalness={0}
                >
                    <meshStandardMaterial color={props.colour} />
                </mesh>
                <mesh
                    geometry={nodes.mesh_1.geometry}
                    material={nodes.mesh_1.material}
                    material-metalness={0}
                />
            </group>


        </group>
    );
}

export default VintageTop;

