/* eslint-disable react/prop-types */
/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useRef, useEffect, useLayoutEffect } from "react";
import { useGLTF, Text } from "@react-three/drei";
import { useFrame, useThree } from "@react-three/fiber";

import vintageBottomScene from "../assets/3d/VINTAGE-BOTTOM.glb";
import interFont from '../assets/fonts/Inter.ttf';

const VintageBottom = ({ showLicense, license, ...props }) => {

    const vintageBottom = useRef();
    const { nodes, materials } = useGLTF(vintageBottomScene);

    return (
        <group ref={vintageBottom} {...props} dispose={null}>

            {/* <group position={[0, 0.002, 0]}>
                <mesh
                    geometry={nodes.mesh_0.geometry}
                    material={nodes.mesh_0.material}
                    position={[0, -0.002, 0]}
                    material-metalness={0}
                >
                    <meshStandardMaterial color={props.colour} />
                </mesh>
                <mesh
                    geometry={nodes.mesh_1.geometry}
                    material={nodes.mesh_1.material}
                    material-metalness={0}
                >
                    <meshStandardMaterial color="#FFF" />
                    {showLicense && (
                        <>
                            <Text
                                position={[0, 0.46, 2.11]}
                                color="#000000"
                                fontSize={0.08}
                                font={interFont}
                            >
                                {license}
                            </Text>
                        </>
                    )}
                </mesh>
                <mesh
                    geometry={nodes.mesh_2.geometry}
                    material={nodes.mesh_2.material}
                    material-metalness={0}
                >
                    <meshStandardMaterial color="#FFF" />
                    {showLicense && (
                        <>
                            <Text
                                position={[0, 0.49, -1.31]}
                                color="#000000"
                                fontSize={0.08}
                                rotation={[0, Math.PI, 0]}
                                font={interFont}
                            >
                                {license}
                            </Text>
                        </>
                    )}
                </mesh>
                <mesh
                    geometry={nodes.mesh_3.geometry}
                    material={nodes.mesh_3.material}
                    material-metalness={0}
                />
            </group> */}

            <mesh
                material-metalness={0}
                geometry={nodes.mesh_0.geometry}
                material={nodes.mesh_0.material}
            />
            <mesh
                material-metalness={0}
                geometry={nodes.mesh_1.geometry}
                material={nodes.mesh_1.material}
            />
            <mesh
                material-metalness={0}
                geometry={nodes.mesh_2.geometry}
                material={nodes.mesh_2.material}
            />
            <mesh
                material-metalness={0}
                geometry={nodes.mesh_3.geometry}
                material={nodes.mesh_3.material}
                >
                <meshStandardMaterial color={props.colour} />
            </mesh>

        </group>
    );
}

export default VintageBottom;
