/* eslint-disable react/prop-types */
/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useRef, useEffect, useLayoutEffect } from "react";
import { useGLTF, Text } from "@react-three/drei";
import { useFrame, useThree } from "@react-three/fiber";

import vintageBottomScene from "../assets/3d/VINTAGE-BOTTOM.glb";

const VintageBottom = ({showLicense,license, ...props}) => {

    const vintageBottom = useRef();
    const { nodes, materials } = useGLTF(vintageBottomScene);

    return (
        <group ref={vintageBottom} {...props} dispose={null}>

                {/* Front License
               {showLicense && (
                <>
                <Text
                    position={[0,0.402,2.39]}
                    color="#000000"
                    fontSize={0.08}
                >
                    {license}
                </Text>
                </>
                )}
             */}

            {/* Back License
            
            {showLicense && (
                <>
                <Text
                    position={[0,0.428,-1.19]}
                    color="#000000"
                    fontSize={0.08}
                    rotation={[0, Math.PI,0]}
                >
                  {license}
                </Text>
                </>
                )}
             */}


        </group>
    );
}

export default VintageBottom;
